[package]
name = "ebx_server"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Ryan X. Charles <ryan@ryanxcharles.com>"]

[dependencies]
"ebx_lib" = { path = "../ebx_lib" }
hex = "0.4.3"
actix-web = "4.5.1"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
